### ISSUE TITLE
DropItem Bug

### ISSUE THREAD

**Issue by Iverins** [MIdCoard/DropItem#1]
丢掉消耗耐久的物品后
再次捡起来，耐久会重置
Paper 1.10.2

**Comment by MidCoard** [comment]
我正在尝试修复这个bug。
前段时间 我用paper的1.14测试没有这个问题。
我先要测试一下。 有可能是服务端的问题。
建议使用非BETA的服务端。

**Comment by Iverins** [comment]
不是BETA的服务端&nbsp;
&nbsp;

Later项目制作中···


&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by MidCoard** [comment]
ok 行 我具体看看怎么回事。

**Comment by Iverins** [comment]
好，而且这个邮箱我也很久没用了
iverins@protonmail.com
&nbsp;
&nbsp;

Later项目制作中···


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sumijie"<notifications@github.com&gt;; 
发送时间: 2020年2月8日(星期六) 下午2:10
收件人: "MIdCoard/DropItem"<DropItem@noreply.github.com&gt;; 
抄送: "later.sky"<1509814509@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MIdCoard/DropItem] DropItem Bug (#1)




ok 行 我具体看看怎么回事。
 
&mdash;

**Comment by MidCoard** [comment]
我用1.10.2paperspigot测试了一下。耐久值没问题啊。

**Comment by Iverins** [comment]
我用1.12.2Paperspigot测试过了，有问题。
可能是插件导致引发的BUG吧


&nbsp;

Later项目制作中···


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sumijie"<notifications@github.com&gt;; 
发送时间: 2020年2月8日(星期六) 晚上6:49
收件人: "MIdCoard/DropItem"<DropItem@noreply.github.com&gt;; 
抄送: "later.sky"<1509814509@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MIdCoard/DropItem] DropItem Bug (#1)




我用1.10.2paperspigot测试了一下。耐久值没问题啊。
 
&mdash;

**Comment by MidCoard** [comment]
啊？ 我能进你服务器看看么？

**Comment by Iverins** [comment]
这是以前的端了，没有了，当时我的的确确测试出了这个BUG
应该是其他插件导致的，我再去用1.12.2的paper端试试
&nbsp;

Later项目制作中···


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sumijie"<notifications@github.com&gt;; 
发送时间: 2020年2月8日(星期六) 晚上6:51
收件人: "MIdCoard/DropItem"<DropItem@noreply.github.com&gt;; 
抄送: "later.sky"<1509814509@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MIdCoard/DropItem] DropItem Bug (#1)




啊？ 我能进你服务器看看么？
 
&mdash;

**Comment by MidCoard** [comment]
可能就是。我觉得应该是其他插件和我的插件在这方面有些冲突。应该不是插件本身的问题= =

**Comment by Iverins** [comment]
恩，那到时候我尝试一下，是否有插件与他冲突



Later项目制作中···


&nbsp;




------------------&nbsp;Original&nbsp;------------------
