### ISSUE TITLE
8.6版本背包满时右击掉落物，盔甲架消失，但不会获得物品

### ISSUE THREAD

**Issue by Zephyr-Q** [MIdCoard/DropItem#2]
在normal状态下，玩家背包满时，shift+移动不会使得问题发生，仅右击时发生问题

**Comment by Zephyr-Q** [comment]
在normal状态下，玩家背包满时，shift+移动不会使得问题发生，仅右击时发生问题

**Comment by MidCoard** [comment]
在最新版本8.7已经修复了
